name: RSS Bot

# Запуск каждые 30 минут
on:
  schedule:
    - cron: '0/30 * * * *'  # Каждые 30 минут (0, 30-я минута каждого часа)
  workflow_dispatch:  # Возможность ручного запуска

jobs:
  run-rss-bot:
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Запускаем скрипт
      - name: Run RSS bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          START_DATE: ${{ secrets.START_DATE }}
        run: python rss_bot.py

      # Сохраняем изменения в sent_posts.json
      - name: Commit sent_posts.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sent_posts.json || true
          git commit -m "Update sent_posts.json" || true
          git push || true
